param([Parameter(Mandatory=$true)][int]$N)
# build_pack.ps1 -- assemble onto_session_pack_vN.zip, foldered by importance, from the REAL disk.
# Claude reads ONLY this zip on intake (git is blind). 00_SESSION/ opens first.
# Founder runs:  .\build_pack.ps1 -N 107
$ErrorActionPreference = "Stop"

$root  = "C:\Projects\onto-research"
$dpo   = Join-Path $root "lab\dpo"
$dl    = "C:\Users\Arist\Downloads"
$guard = "f888f427597c7c45e6503c33f1babe24"   # PACK_SPEC staleness guard

# carried docs by folder (read order = folder number). STRUCTURE.md is generated below.
$carry = [ordered]@{
  "00_SESSION" = @("00_SESSION_PACK.md","CONTINUITY_LOG.md")
  "01_CANON"   = @("ARCHITECTURE_master.md","STATUS.md")
  "02_SPEC"    = @("SPEC_disposition_audit.md","SPEC_selfcheck_A.md")
  "03_REF"     = @("PACK_SPEC.md")
}

function Find-One($name){
  $hits = Get-ChildItem -Path $root -Recurse -File -Filter $name -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -notmatch '\\(\.git|_backup|__pycache__|adapters|node_modules)\\' }
  if(-not $hits){ return $null }
  $pref = $hits | Where-Object { $_.FullName -match '\\reports\\' } | Select-Object -First 1
  if($pref){ return $pref } else { return ($hits | Select-Object -First 1) }
}

$stage = Join-Path $env:TEMP ("packstage_v{0}" -f $N)
if(Test-Path $stage){ Remove-Item $stage -Recurse -Force }
foreach($d in $carry.Keys){ New-Item -ItemType Directory -Force -Path (Join-Path $stage $d) | Out-Null }

# locate + copy carried docs ; collect any missing (non-fatal -> report, then refuse to zip)
$missing = @()
foreach($d in $carry.Keys){
  foreach($n in $carry[$d]){
    $src = Find-One $n
    if($null -eq $src){ $missing += ("{0}\{1}" -f $d,$n); continue }
    Copy-Item $src.FullName -Destination (Join-Path $stage (Join-Path $d $n)) -Force
    Write-Host ("carry  {0}\{1}  <- {2}" -f $d,$n,$src.FullName)
  }
}
if($missing.Count -gt 0){
  Write-Host ""
  Write-Host "MISSING (place these on disk, then re-run) :"
  $missing | ForEach-Object { Write-Host ("   - " + $_) }
  Write-Host "NOT zipping. (00_SESSION_PACK.md = the routing doc Claude hands you at close ; PACK_SPEC.md -> reports\ref\.)"
  exit 1
}

# PACK_SPEC staleness guard
$ps = Join-Path $stage "03_REF\PACK_SPEC.md"
$psmd5 = (Get-FileHash $ps -Algorithm MD5).Hash.ToLower()
if($psmd5 -ne $guard){
  Write-Host ("CONVEYOR DRIFT: PACK_SPEC md5 {0} != {1}. STOP, reconcile before shipping." -f $psmd5,$guard)
  exit 2
}
Write-Host "PACK_SPEC guard OK"

# STRUCTURE.md = full on-disk map of lab\dpo (REAL paths, not recollection)
$struct = Join-Path $stage "00_SESSION\STRUCTURE.md"
$lines  = @()
$lines += "# STRUCTURE.md -- on-disk file map of lab\dpo (auto-generated by build_pack.ps1)"
$lines += ("generated : {0}" -f (Get-Date -Format "yyyy-MM-dd HH:mm"))
$lines += ("root      : {0}" -f $dpo)
$lines += "excludes  : .git, _backup, __pycache__, adapters, *.bin/.safetensors/.pt/.zip (weights/archives)"
$lines += ""
$files = Get-ChildItem -Path $dpo -Recurse -File -ErrorAction SilentlyContinue |
  Where-Object { $_.FullName -notmatch '\\(\.git|_backup|__pycache__|adapters)\\' -and
                 $_.Extension -notmatch '^\.(bin|safetensors|pt|zip)$' } |
  Sort-Object FullName
foreach($f in $files){
  $rel = $f.FullName.Substring($dpo.Length).TrimStart('\')
  $lines += ("{0,8:N1} KB  {1}" -f ($f.Length/1KB), $rel)
}
$lines | Set-Content -Path $struct -Encoding UTF8
Write-Host ("STRUCTURE.md written ({0} files mapped)" -f $files.Count)

# MANIFEST.md5 over staging (foldered relative paths, forward slashes ; excludes itself)
$man = Join-Path $stage "MANIFEST.md5"
$ml  = @()
Get-ChildItem -Path $stage -Recurse -File | Where-Object { $_.Name -ne "MANIFEST.md5" } | ForEach-Object {
  $rel = $_.FullName.Substring($stage.Length).TrimStart('\').Replace('\','/')
  $h   = (Get-FileHash $_.FullName -Algorithm MD5).Hash.ToLower()
  $ml += ("{0}  {1}" -f $h,$rel)
}
$ml | Set-Content -Path $man -Encoding ASCII
Write-Host "MANIFEST.md5 written"

# zip (preserve folder layout)
$zip = Join-Path $dl ("onto_session_pack_v{0}.zip" -f $N)
if(Test-Path $zip){ Remove-Item $zip -Force }
Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -Force
Write-Host ""
Write-Host ("PACK v{0} BUILT -> {1}" -f $N,$zip)
Write-Host "contents (read order = folder number):"
Get-ChildItem -Path $stage -Recurse -File | ForEach-Object {
  Write-Host ("  " + $_.FullName.Substring($stage.Length).TrimStart('\').Replace('\','/'))
}
Write-Host ""
Write-Host "Upload this zip at the start of the next session."
